showing the amount of names registered and name duplicates
alexfelipe/bora-pro-fut pull request #6
Opened 2024-01-27 03:33 UTC by ThailanDev

2024-01-27 20:01 UTC, alexfelipe requested changes
Há detalhes que precisam de analise e ajuste, qualquer dúvida é só avisar

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                modifier.padding(16.dp),
modifier padrão deve ser usado apenas no root do composable

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                modifier.fillMaxWidth()
outro uso do modifier padrão

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    Row(modifier = modifier.padding(top = 10.dp, start = 16.dp, end = 16.dp)) {
não é necessário colocar label do modifier, se preferir manter não é um problema

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    Row(modifier = modifier.padding(top = 10.dp, start = 16.dp, end = 16.dp)) {
a partir de 3 parâmetros, vamos tentar manter em linhas separadas

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    amountPlayers = if (uiState.players.isNotBlank()) "${
esse código é custoso e perigiso, pois vai executar a cada recomposição, o ideal é que seja feito por um state holder apenas nos momentos que devem acontecer, ou então, utilize o remember para controlar também os momentos que devem acontecer

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +        NamesDuplicates(player = uiState.players)
se não me engano, o correto seria DuplicateNames

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun findAllDuplicates(array: List<Player>): Set<Player> {
acredito que há muito código de gerenciamento de estado nos composables, o ideal é que isso seja movido para o viewmodel lidar com o estado

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    LazyRow(
O ideal é que a tela receba os dados e exiba e não tenha que ficar fazendo analises/processamentos, ou seja, o ideal é que o ViewModel se responsabilize por isso

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +            if (index != 0) Text(text = ", ", fontSize = 12.sp)
acredito que dê para simplificar/abstrair o código, ou seja, não precisa ficar verificando o index para decidir o texto que deve ser exibido

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
Notei que tem muitas extrações de composables, talvez, se remover as responsabilidades de gerenciamento de estado, processamento de dados etc e jogar para o viewmodel e ui state, vai simplifcar a ponto de não precisar dos composables extras

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +fun String.parseToPlayers(duplicityEnabler: Boolean = true): List<Player> {
fiquei na duvida sobre a nomeação, nao parece um 'habilitador' de duplicidade, seria mais para um set de configuração, então imagino que o nome enableDuplicity seria mais apropriado

2024-01-27 20:01 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +fun String.parseToPlayers(duplicityEnabler: Boolean = true): List<Player> {
Acredito que criar 2 métodos seria mais interessante para ter um melhor significado, por exemplo:

String.parseToUniquePlayers()
String.parseToPlayersWithDuplicates()

Se preferir manter do jeito que tá, o ideal é que a opção de duplicidade não tenha um valor padrão, e quem chamar seja responsável em decidir

2024-01-29 01:33 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                modifier.padding(16.dp),
feito

2024-01-29 01:33 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                modifier.fillMaxWidth()
ajustado

2024-01-29 01:33 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    Row(modifier = modifier.padding(top = 10.dp, start = 16.dp, end = 16.dp)) {
ajustado

2024-01-29 01:33 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    amountPlayers = if (uiState.players.isNotBlank()) "${
Ajustado

2024-01-29 01:33 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +        NamesDuplicates(player = uiState.players)
rs ajsutado

2024-01-29 01:34 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun findAllDuplicates(array: List<Player>): Set<Player> {
extraido para viewmodel

2024-01-29 01:34 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    LazyRow(
ajustado

2024-01-29 01:34 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +            if (index != 0) Text(text = ", ", fontSize = 12.sp)
Stateholder fara o tratamento dentro do viewmodel.

2024-01-29 01:35 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
feito

2024-01-29 01:35 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +fun String.parseToPlayers(duplicityEnabler: Boolean = true): List<Player> {
Criei os dois metodos conforme sugerido

2024-01-29 03:05 UTC, alexfelipe approved these changes
Fiz alguns comentários, veja se faz sentido alterar, caso não haja necessidade, me avisa pra fazer o merge

2024-01-29 03:05 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun DuplicateNames(modifier: Modifier = Modifier, duplicateNames: List<Player>) {
Refleti bastante se é necessário ser um composable extraído, parece um código muito simples para extrair para uma nova função, geralmente fazemos isso quando tem algo um pouco mais complexo, ou uso de algum slot etc... Acho que se colocasse direto um flow layout dentro da screen já seria o suficiente

2024-01-29 03:05 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun NamesDuplicatesPreview() {
acho que esqueci de mencionar, talvez eu precise revisar isso nos meus códigos tbm, mas vou aproveitar pra mencionar, previews devem ser privados

2024-01-29 03:05 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +                repository.save(it.toSet())
que estranho, não era pra ser um set?

2024-01-29 12:17 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +                repository.save(it.toSet())
isso gerou uma redundância.
removido

2024-01-29 12:17 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun NamesDuplicatesPreview() {
adicionei private em todos

2024-01-29 12:17 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +fun DuplicateNames(modifier: Modifier = Modifier, duplicateNames: List<Player>) {
esqueci de remover esse cara.
feito

2024-01-29 13:21 UTC, alexfelipe approved these changes

2024-01-29 13:22 UTC, merged