Feat/addting clear button
alexfelipe/bora-pro-fut pull request #8
Opened 2024-01-31 03:41 UTC by ThailanDev

2024-01-31 12:02 UTC, Metallikl reviewed
Conforme conversamos, verificar a possibilidade de extrair os botões de estão repetidos e regra para colocar os argumentos e linhas separadas.

2024-01-31 12:28 UTC, alexfelipe requested changes
Há detalhes que precisam de ajuste

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersNavigation.kt
> -            viewModel.isPlayersSaved.collectLatest {
pq mudar a abordagem de navegação?

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    onClear: () -> Unit,
o evento precisa ser mais claro, por exemplo, `onClearPlayers` ou algo similar

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                    modifier = Modifier
aproveita para remover as labels de modifier

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                    top = 8.dp, start = 8.dp, bottom = 8.dp, end = 2.dp
acredito que dê para simplificar essa abordagem de espaçamento, pode tentar aplicar o que for necessário diretamente no parent (`Row`) e se precisar de algo entre os componentes, use um `Spacer`

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                    .padding(top = 8.dp, start = 2.dp, bottom = 8.dp, end = 4.dp),
o comentário acima vale pra essa parte também.

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                    .clickable {}
remover `clickable` sem uso

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                contentDescription = null,
indicar que é um ícone para limpar o campo

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                .background(Color(0xFF8B0000))
na ultima refatoração, precisamos nomear essas cores que colocamos como hard coded

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                        visible = uiState.players.isNotBlank() && uiState.amountPlayers.isNotBlank() && uiState.amountPlayers.toInt() > 3,
talvez seria mais interessante extrair essa condição para uma função, apenas para não ficar tão grande na leitura, pode até ser um nome como `isSabeButtonVisible()` ou se achar um nome melhor

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                        Row(
Neste Row se aplica os mesmo detalhes acima

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +    fun clearField() {
para o viewmodel, não seria field, seria apenas players mesmo

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
>  private fun findAllDuplicates(array: List<Player>): Set<Player> {
o nome indica ser um array, mas é uma lista. Dado que é uma lista de jogadores, o ideal é que o nome diga isso, então poderia ser `players`

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
>      val seen: MutableSet<Player> = mutableSetOf()
não entendi o significado para essa variável, talvez faça mais sentido colocar um nome mais descritivo

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
>      val seen: MutableSet<Player> = mutableSetOf()
Vendo o código inteiro parece possível fazer sem a criação desta lista

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +    return listFormated
Acredito que de para simplificar mais esse código, talvez fazer apenas em uma chamada encadeada sem a necessidade de devolver variáveis

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/models/Player.kt
> +    var name: String,
pq ser mutável?

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/res/values/colors.xml
> +    <color name="black_green">#006400</color>
pq criar as cores no xml? poderia ser criado no arquivo de cores

2024-01-31 12:28 UTC, alexfelipe commented on app/src/main/res/values/strings.xml
> +    <string name="players">Lista de jogadores</string>
é bom mudar o nome para ser mais preciso com o valor `players list` por exemplo

2024-02-01 01:18 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersNavigation.kt
> -            viewModel.isPlayersSaved.collectLatest {
Desfiz alteração.
Modifiquei apenas para facilitar os testes, pq sempre que eu estrava no app estava sempre sendo redirecionado.

2024-02-01 01:18 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +    onClear: () -> Unit,
ajustado

2024-02-01 01:18 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                    modifier = Modifier
ajustado

2024-02-01 01:18 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                    top = 8.dp, start = 8.dp, bottom = 8.dp, end = 2.dp
ajustado

2024-02-01 01:18 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                                    .padding(top = 8.dp, start = 2.dp, bottom = 8.dp, end = 4.dp),
ajustado

2024-02-01 01:19 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
>      val seen: MutableSet<Player> = mutableSetOf()
ajustado

2024-02-01 01:19 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +    return listFormated
ajustado

2024-02-01 01:19 UTC, ThailanDev commented on app/src/main/java/br/com/alexf/boraprofut/models/Player.kt
> +    var name: String,
desfiz a moficação.

2024-02-01 01:19 UTC, ThailanDev commented on app/src/main/res/values/colors.xml
> +    <color name="black_green">#006400</color>
ajustado

2024-02-01 01:19 UTC, ThailanDev commented on app/src/main/res/values/strings.xml
> +    <string name="players">Lista de jogadores</string>
ajustado

2024-02-01 01:39 UTC, alexfelipe requested changes
Mais alguns detalhes e finalizamos

2024-02-01 01:39 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +                    DrawSaveClearButtons(
O nome parece confuso por induzir duas possibilidades de ações, sendo que só existe uma ação de clique. Acredito que da pra seguir com essas possibilidades:

- Usar um nome mais genérico para reutilizar o botão, um exemplo, `ActionButton`
- Não extrair o botão e manter do jeito que tava
- Criar um botão para cada ação

Se achar necessário, podemos trocar ideia para sugerir abordagens

2024-02-01 01:39 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersScreen.kt
> +private fun DrawSaveClearButtons(
avaliando bem, acho que extrair um componente e encapsular a animação não é uma boa, até mesmo o Modifier padrão não parece aproveitar bem o benefício dele

2024-02-01 01:39 UTC, alexfelipe commented on app/src/main/java/br/com/alexf/boraprofut/features/players/PlayersViewModel.kt
> +private fun formatAndReturnDuplicates(array: List<Player>): Set<Player> {
Essa etapa parece fazer passos demais para a proposta, talvez, vai ser interessante fazer um pair para tirar dúvidas

2024-02-01 16:03 UTC, alexfelipe approved these changes
de boas

2024-02-01 16:03 UTC, merged